#popclip
name: RottenTomatoes
identifier: com.pilotmoon.popclip.extension.rotten-tomatoes
description: Search movie data on RottenTomatoes.
icon: rottentomatoes-svgrepo-com.svg
url: http://rottentomatoes.com/search?search={popclip text}
popclipVersion: 3785
